name: Build OpenWrt package
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget
          wget https://downloads.openwrt.org/releases/21.02.3/targets/x86/64/openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz -P ../
          tar -xf ../openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz -C ../
      - name: Build package
        run: |
          cd ../openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64
          bash -c "${{ github.workspace }}/build.sh"
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: luci-app-nauta
          path: luci-app-nauta*.ipk
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "luci-app-nauta*.ipk"
          tag: ${{ github.ref_name }}
